name: ci

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Run cargo check --all
      env:
        RUSTFLAGS: -D warnings
      run: |
        cargo check --all
    - name: Run the tests
      env:
        RUSTFLAGS: -D warnings
      run: |
         cargo test --all
    - name: Run cargo doc
      run: |
        cargo doc --all --all-features
